# Generated by Django 2.1.1 on 2021-07-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
