# Generated by Django 2.1.1 on 2021-07-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_venue_venue_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_cost',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
