# Generated by Django 3.2.5 on 2021-07-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_studio_photo_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='photo_promo',
            field=models.ImageField(blank=True, default='nonr', upload_to='photos/studio/%Y/%m/%d/'),
        ),
    ]
