# Generated by Django 2.1.1 on 2021-06-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20210627_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bubbly',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
