# Generated by Django 2.1.1 on 2021-06-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_bubbly'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
