# Generated by Django 3.2.5 on 2021-07-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20210714_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='added_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
