# Generated by Django 3.2.5 on 2021-09-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_auto_20210715_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
