# Generated by Django 3.2.5 on 2021-09-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_booking_booking_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_quantity',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
